# Generated by Django 3.0.2 on 2020-12-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
